name: Question
description: Ask a question about this project
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Questions
      description: Please tell us about your question.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this Issue, you are agreeing to the Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
